version: '3'
services:
  service:
    build: ./
    command: sh -c "npm install && node index.js"
    environment:
      - NODE_ENV=sandbox
      - PORT=3000
    env_file:
      - .env
    ports:
      - '3000:3000'
    working_dir: /root
    volumes:
      - ./:/root:cached # <-- maps local ./ to /root inside container.
